### ISSUE TITLE
Path in the EASM executable file not accessing the Git repository

### ISSUE THREAD

**Issue by Merrci** [g0ldencybersec/EasyEASM#13]
Hi,

I have a slight issue when running the EasyEASM tool.

When I run the command .\easyeasm I get the error below:
![Screenshot 2024-01-30 105519](https://github.com/g0ldencybersec/EasyEASM/assets/158079481/eee3e33a-934d-433a-9648-5c76a45dc298)

Panic: exit status 2
goroutine 20 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/passive/amass.RunAmass({0xc0000a8a28, 0x6}, 0x0?, 0x0?)
/home/mercy/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/pkg/passive/amass/amass.go:26 +0x411
created by github.com/g0ldencybersec/EasyEASM/pkg/passive.(*PassiveRunner).RunPassiveEnum in goroutine 1
/home/mercy/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/pkg/passive/passive.go:27 +0xcc

if you put "github.com/g0ldencybersec/EasyEASM/pkg/passive/amass" in the browser, the path returns 404

But

this is the link you get when you go through the github "github.com/g0ldencybersec/EasyEASM/tree/main/pkg/passive/amass" 

It seems the link in the executable file needs to include "tree/main" before the "pkg".

Thank you and I look forward to your response.

**Comment by d4rk30** [comment]
Check to see if the `bin` directory in your `go env` environment contains the `oam_subs` tool

**Comment by d4rk30** [comment]
I have just submitted a new fix that should resolve such dependency issues and await merging
