### ISSUE TITLE
Abnormal termination

### ISSUE THREAD

**Issue by eduardoellery** [g0ldencybersec/EasyEASM#18]
Hi!

I installed EasyASM in two different linux, but got the same following error. Can you guys help me solve it?

```
goroutine 1 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/passive/httpx.RunHttpx({0xc000126180?, 0xc000056058?, 0xc00002be18?})
	/home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/pkg/passive/httpx/httpx.go:16 +0x185
github.com/g0ldencybersec/EasyEASM/pkg/passive.(*PassiveRunner).RunHttpx(...)
	/home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/pkg/passive/passive.go:59
main.main()
	/home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/easyeasm/main.go:60 +0xf9c
```

**Comment by eduardoellery** [comment]
g0lden gave this tip on discord and solved the issue!

> So Kali comes with a pre-installed "httpx" that is not the same as Project Discovery's tool httpx. You have to delete that and add the right httpx to $PATH
