### ISSUE TITLE
amass error !

### ISSUE THREAD

**Issue by 0xsheet** [g0ldencybersec/EasyEASM#20]
./main
All needed tools installed!
****************

EASY EASM

***************

No previous run data found
Running Passive Sources
Finding domains for aon.com
Runing Subfinder on aon.com
Running Amass on aon.com
panic: exit status 2

goroutine 7 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/passive/amass.RunAmass({0xc00001e808, 0x7}, 0x0?, 0x0?)
        /home/kali/EasyEASM/pkg/passive/amass/amass.go:18 +0x427
created by github.com/g0ldencybersec/EasyEASM/pkg/passive.(*PassiveRunner).RunPassiveEnum
        /home/kali/EasyEASM/pkg/passive/passive.go:27 +0xcd

**Comment by gamix255** [comment]
@iq-rasco 
EasyEASM is structured to build and run multiple external programs.
I encountered several errors, including the one you mentioned.
You can pinpoint where the error occurred by directly calling the executable file called from within.

One is that amass has changed to use postgres by default.
The following URL is helpful:
https://medium.com/@RISHII_R_MAKHIJA/step-by-step-guide-installing-and-migrating-from-amass-v3-to-v4-on-linux-6fbea84c150d

In my case, the amass configuration file was .config/amass/config.yaml in the home directory, so I stored the connection information for the database I created here.

Another is that some functions are missing in the database.
When you run an external program, the following error is displayed:
operator class "gin_trgm_ops" does not exist for access method "gin"

This was resolved by following the steps below.
https://github.com/owasp-amass/amass/issues/1036
Good luck.

**Comment by GitCyberOps** [comment]
Hello everyone I have the following error: 

ubnt@ubnt:~/go/bin$ ./easyeasm 
All needed tools installed!
******

EASY EASM

*****

No previous run data found
Running Passive Sources
Finding domains for mavi.mx
Runing Subfinder on mavi.mx
Running Amass on mavi.mx
panic: exit status 2

goroutine 8 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/passive/amass.RunAmass({0xc000014ab8, 0x7}, 0xc00002a3f0, 0x0?)
	/home/ubnt/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/pkg/passive/amass/amass.go:26 +0x405
created by github.com/g0ldencybersec/EasyEASM/pkg/passive.(*PassiveRunner).RunPassiveEnum in goroutine 1
	/home/ubnt/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.6/pkg/passive/passive.go:27 +0xc

I appreciate your kind support
